### ISSUE TITLE
Wallets Created in Cakeshop Locked with no Ability to Unlock

### ISSUE THREAD

**Issue by Bschuster3434** [jpmorganchase/cakeshop#24]
#### Description of problem

I am attempting to run the ballot smart contract with multiple accounts. I have created multiple account via the Wallet tab in Cakeshop. However, as soon as I attempt to execute a contract function via the sandbox, I get an error and this message appears in my console, saying that my address is locked.

It seems like the root of this issue is that the new addressed is 'locked'. However, I did not see a way in the GUI to unlock it.

#### Expected behavior

Accounts created in the Cakeshop GUI should be unlocked by default or given a way to unlock via the interface.

#### Actual behavior

I get this error in the console:

```
WARN 2017-03-31 12:07:54,680 [qtp1942106014-19] (JsonMethodArgumentResolver.java:128) Param type mismatch for 'privateFor'; got class java.lang.String
DEBUG 2017-03-31 12:07:54,687 /cakeshop/api/contract/transact
 WARN 2017-03-31 12:07:54,740 [qtp1942106014-21] (BaseController.java:35 ) Caught exception: RPC request failed: account is locked
com.jpmorgan.cakeshop.error.APIException: RPC request failed: account is locked
	at com.jpmorgan.cakeshop.service.impl.GethHttpServiceImpl.processResponse(GethHttpServiceImpl.java:197)
	at com.jpmorgan.cakeshop.service.impl.GethHttpServiceImpl.executeGethCall(GethHttpServiceImpl.java:163)
	at com.jpmorgan.cakeshop.service.impl.GethHttpServiceImpl.executeGethCall(GethHttpServiceImpl.java:144)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy86.executeGethCall(Unknown Source)
	at com.jpmorgan.cakeshop.service.impl.ContractServiceImpl.transact(ContractServiceImpl.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy98.transact(Unknown Source)
	at com.jpmorgan.cakeshop.controller.ContractController$1.call(ContractController.java:201)
	at com.jpmorgan.cakeshop.controller.ContractController$1.call(ContractController.java:194)
	at org.springframework.web.context.request.async.WebAsyncManager$4.run(WebAsyncManager.java:317)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

#### Steps to reproduce the behavior

Launch the 7nodes example on as explained in the tutorial. Create a new account via the wallet tab. Go to the sandbox and execute the ballot contract, and give permission to your new account to vote. Then switch to that account and attempt to vote on the contract.

#### System information

Cakeshop version or commit hash: Cakeshop 0.9.1 Build 6c7a88ee

Geth/Quorum version testing against: 1.5.9-Stable

Cakeshop OS & Version: Linux

Browser OS & Version: Ubuntu 16.04, Chrome 57.0.2987.110 (64-bit)

**Comment by tylobban** [comment]
Hi @Bschuster3434, in cakeshop v0.9.x accounts must be created through cakeshop-api otherwise cakeshop simply ignores them. This is obviously less than ideal so we’re going to add / expand wallet handling for the next release and address this issue.

**Comment by Bschuster3434** [comment]
Hey @tylobban, thank you for the response. Is the api a command line tool, or does it need to be scripted in another language?

**Comment by tylobban** [comment]
Hi - you can find the api details on the API tab of the cakeshop app (`wallet/create`).
