### ISSUE TITLE
Unable to run cakeshop

### ISSUE THREAD

**Issue by MitchK** [jpmorganchase/cakeshop#61]
#### Description of problem

I would like to run Cakeshop 0.9.1 (on Mac High Sierra), but I get a NullPointerException.

#### Expected behavior

Cakeshop runs and serves the web app

#### Actual behavior

Throws NullPointerException.

#### Steps to reproduce the behavior

1. Download Cakeshop 0.9.1 war file
2. ```java -jar cakeshop-0.9.1-x86_64-macOS.war```

#### System information

Cakeshop version or commit hash: 0.9.1

Cakeshop runtime configuration: stand alone

Geth/Quorum version testing against: 
$ geth version
Geth
Version: 1.7.3-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.2
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.9.2/libexec

Cakeshop OS & Version: OSX

Browser OS & Version: Chrome

#### Backtrace/logs

Copy all relevant log output. Use [Gist](https://gist.github.com/) for longer logs.

```
$ java -jar cakeshop-0.9.1-x86_64-macOS.war
Defaulting to spring profile: local
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at com.jpmorgan.cakeshop.config.SpringBootApplication.extractGeth(SpringBootApplication.java:73)
	at com.jpmorgan.cakeshop.config.SpringBootApplication.main(SpringBootApplication.java:48)
	... 6 more
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 1 more
Caused by: java.lang.NullPointerException
	at com.jpmorgan.cakeshop.config.SpringBootApplication.extractGeth(SpringBootApplication.java:73)
	at com.jpmorgan.cakeshop.config.SpringBootApplication.main(SpringBootApplication.java:48)
	... 6 more
```

**Comment by melnicorn** [comment]
I had the same problem with Java 9 as my JDK. Installed Java 8 JDK, and it works fine.
