### ISSUE TITLE
I got "java.lang.IndexOutOfBoundsException: Index: 0, Size: 0" when trying to run in attach mode

### ISSUE THREAD

**Issue by spksoft** [jpmorganchase/cakeshop#71]
#### Description of problem
I got "java.lang.IndexOutOfBoundsException: Index: 0, Size: 0" when trying to run in attach mode for quorum private network

#### Expected behavior
I should run correctly without any error

#### Actual behavior
```
root@quorum-node-02:~# java -jar cakeshop.war
Defaulting to spring profile: local
Extracting geth to /root/data/geth
 INFO 2018-06-04 04:40:58,587 [main] (StartupInfoLogger.java:48 ) Starting SpringBootApplication on quorum-node-02 with PID 13786 (started by root in /root)
 INFO 2018-06-04 04:40:58,595 [main] (SpringApplication.java:670) The following profiles are active: container,spring-boot,local
 INFO 2018-06-04 04:41:05,334 [main] (AppConfig.java:113) eth.config.dir=/root/data/local
 INFO 2018-06-04 04:41:05,347 [main] (AppConfig.java:144) Loading config from /root/data/local/application.properties


********************************************************************************
Running pre-flight checks...

Testing ethereum data dir path
/root/.ethereum
OK

Testing db path
/root/data/local/db
OK

Testing geth server binary
OK

Testing solc compiler binary
OK

ALL TESTS PASSED!
********************************************************************************

 INFO 2018-06-04 04:41:29,738 [main] (BlockchainInitializerTask.java:120) Contract registry address not found
 INFO 2018-06-04 04:41:29,744 [main] (BlockchainInitializerTask.java:149) ContractRegistry not found on chain
 INFO 2018-06-04 04:41:29,752 [main] (BlockchainInitializerTask.java:154) Deploying ContractRegistry to chain
ERROR 2018-06-04 04:41:32,314 [main] (SpringApplication.java:827) Application startup failed
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.jpmorgan.cakeshop.service.impl.ContractServiceImpl.getAddress(ContractServiceImpl.java:326)
	at com.jpmorgan.cakeshop.service.impl.ContractServiceImpl.create(ContractServiceImpl.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy98.create(Unknown Source)
	at com.jpmorgan.cakeshop.service.impl.ContractRegistryServiceImpl.deploy(ContractRegistryServiceImpl.java:66)
	at com.jpmorgan.cakeshop.service.task.BlockchainInitializerTask.deployContractRegistry(BlockchainInitializerTask.java:155)
	at com.jpmorgan.cakeshop.service.task.BlockchainInitializerTask.run(BlockchainInitializerTask.java:76)
	at com.jpmorgan.cakeshop.service.impl.GethHttpServiceImpl.runPostStartupTasks(GethHttpServiceImpl.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy86.runPostStartupTasks(Unknown Source)
	at com.jpmorgan.cakeshop.config.AppStartup.onApplicationEvent(AppStartup.java:118)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at com.jpmorgan.cakeshop.config.SpringBootApplication.main(SpringBootApplication.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 1 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.jpmorgan.cakeshop.service.impl.ContractServiceImpl.getAddress(ContractServiceImpl.java:326)
	at com.jpmorgan.cakeshop.service.impl.ContractServiceImpl.create(ContractServiceImpl.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy98.create(Unknown Source)
	at com.jpmorgan.cakeshop.service.impl.ContractRegistryServiceImpl.deploy(ContractRegistryServiceImpl.java:66)
	at com.jpmorgan.cakeshop.service.task.BlockchainInitializerTask.deployContractRegistry(BlockchainInitializerTask.java:155)
	at com.jpmorgan.cakeshop.service.task.BlockchainInitializerTask.run(BlockchainInitializerTask.java:76)
	at com.jpmorgan.cakeshop.service.impl.GethHttpServiceImpl.runPostStartupTasks(GethHttpServiceImpl.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy86.runPostStartupTasks(Unknown Source)
	at com.jpmorgan.cakeshop.config.AppStartup.onApplicationEvent(AppStartup.java:118)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at com.jpmorgan.cakeshop.config.SpringBootApplication.main(SpringBootApplication.java:68)
	... 6 mor
```

#### Steps to reproduce the behavior
I start geth by following this command
```
nohup geth --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --rpcport 22000 --port 21000 --bootnodes enode://8d6f9303aae8743cb8e2555004215302abd92df51f603580acb5b377cfc472d1241ca91634b164cc1ca7b2e574ba473570115de166d5a9ec70f1199ebd5077fa@127.0.0.1:30301 > geth.log &
```
My genesus.json file
```json
{
  "alloc": {},
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0
  },
  "difficulty": "0x0",
  "extraData": "0x",
  "gasLimit": "0x2FEFD800",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
```
My application.properties files
```
#Mon Jun 04 04:41:29 UTC 2018
cakeshop.database.vendor=hsqldb
cakeshop.hibernate.hbm2ddl.auto=update
cakeshop.hibernate.jdbc.batch_size=20
cakeshop.jdbc.pass=sdk
cakeshop.jdbc.user=sdk
cakeshop.mvc.async.pool.queue.max=2000
cakeshop.mvc.async.pool.threads.core=250
cakeshop.mvc.async.pool.threads.max=1000
contract.poll.delay.millis=5000
contract.registry.addr=
endpoints.actuator.enabled=true
geth.auto.start=false
geth.auto.stop=false
geth.cors.enabled=false
geth.cors.url=
geth.datadir=/root/.ethereum
geth.db.enabled=true
geth.identity=root
geth.log=/logs
geth.mining=true
geth.networkid=1006
geth.node.port=30303
geth.params.extra=
geth.rpcapi.list=admin,db,eth,debug,miner,net,shh,txpool,personal,web3
geth.url=http\://localhost\:22000
geth.verbosity=
management.context-path=/manage
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
spring.main.banner-mode=off
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
```

#### System information

Cakeshop version or commit hash: cakeshop-0.9.1-x86_64-linux

Cakeshop runtime configuration: attach mode

Geth/Quorum version testing against: 
```
Geth
Version: 1.7.2-stable
Git Commit: df4267a25637a5497a3db9fbde4603a3dcd6aa14
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

Cakeshop OS & Version: Linux

Browser OS & Version: OSX

**Comment by fixanoid** [comment]
Hi, if you are attaching to running quorum v2.x and above, cakeshop will not be able to work at the moment. Latest cakeshop v0.10 is only up to Quorum v1.

**Comment by cvkonduru** [comment]
@fixanoid  Is the Cakeshop working now for Quorum V2.x any updates?
